### ISSUE TITLE
large polygon intersection performance issues

### ISSUE THREAD

**Issue by contra** [tidwall/tile38#267]
issue: given a small set of polygons (the whole db is 5mb) in tile38, checking for intersection of another polygon takes ~700ms alone, and more than 1 minute when queries are running concurrently

data: [appendonly.aof.zip](https://github.com/tidwall/tile38/files/1776947/appendonly.aof.zip)

save this as test.sh:

```sh
tile38-cli 'INTERSECTS boundaries IDS OBJECT {"coordinates":[[[[-122.647034001118,47.0899370579489],[-122.647031736625,47.0892849802177],[-122.647028649253,47.0883237290569],[-122.647028239162,47.0883119209585],[-122.647027084432,47.088300135343],[-122.647025186863,47.0882883937944],[-122.64702255095,47.0882767196949],[-122.647019134425,47.0882649880388],[-122.647014972363,47.088253368798],[-122.647010071058,47.0882418853548],[-122.647004506053,47.0882306887953],[-122.647436424352,47.0881232108176],[-122.648094505957,47.0879593453475],[-122.651042646401,47.0872252116743],[-122.651507205593,47.0871095300808],[-122.651510831659,47.0871086280608],[-122.651695829399,47.0870625548931],[-122.651699432083,47.087061658269],[-122.653838766346,47.0865288720099],[-122.653855029686,47.0865245462708],[-122.653859695369,47.0865232251668],[-122.653876392182,47.0865194318264],[-122.653951140233,47.0865007672966],[-122.653964785646,47.0865082037906],[-122.653978910398,47.0865152769585],[-122.653993471322,47.0865219229485],[-122.654008444134,47.0865281282706],[-122.65402379826,47.086533882133],[-122.654039504919,47.0865391719453],[-122.654055535335,47.0865439896135],[-122.65407185803,47.0865483261444],[-122.654088442428,47.0865521707461],[-122.654105255253,47.0865555180228],[-122.654122266829,47.0865583607798],[-122.654139442981,47.0865606954198],[-122.654156753132,47.086562513849],[-122.654174162208,47.0865638169666],[-122.654191637834,47.0865645993768],[-122.654209146735,47.0865648601802],[-122.654226655636,47.0865645993768],[-122.654244132161,47.0865638169666],[-122.654261541237,47.086562513849],[-122.654278851388,47.0865606954198],[-122.65429602664,47.0865583607798],[-122.654313039115,47.0865555180228],[-122.654329851941,47.0865521707461],[-122.654346549654,47.0865482982654],[-122.657664019179,47.0857219571027],[-122.657741724201,47.0857025991957],[-122.657854724016,47.0856746851387],[-122.657966732778,47.0856474779488],[-122.65803182391,47.0856319349659],[-122.65803267197,47.0856317317191],[-122.658079097672,47.0856206466756],[-122.658191866362,47.0855941832251],[-122.658304603575,47.085568187422],[-122.658347994065,47.0855583569327],[-122.658348980621,47.0855581348001],[-122.658417847106,47.0855425369585],[-122.65853111402,47.0855173388542],[-122.658644311686,47.0854926155918],[-122.658758007576,47.0854682421657],[-122.658872053303,47.0854442518508],[-122.658986062157,47.0854207255861],[-122.659100088998,47.0853976516804],[-122.659160776149,47.0853856151541],[-122.659214622157,47.0853749312082],[-122.659329085169,47.0853526792828],[-122.659443847655,47.0853308212605],[-122.659560685777,47.0853090315866],[-122.659576569603,47.0853058282015],[-122.659592246585,47.0853021787526],[-122.65960856928,47.085297843121],[-122.659624598796,47.0852930245535],[-122.659640306355,47.0852877347412],[-122.659655659581,47.0852819808788],[-122.659670632394,47.0852757755566],[-122.659685193317,47.0852691295667],[-122.65969931627,47.0852620572982],[-122.659712974274,47.0852545686435],[-122.659726141248,47.0852466815891],[-122.659738792012,47.0852384096249],[-122.659750902282,47.0852297698381],[-122.659762448678,47.0852207757183],[-122.659773409615,47.0852114470507],[-122.659783766208,47.0852018000231],[-122.659793495074,47.0851918544206],[-122.659802580924,47.0851816282296],[-122.659811003975,47.0851711412352],[-122.659818749835,47.0851604123232],[-122.659825803218,47.0851494630773],[-122.659832149734,47.0851383150812],[-122.659837778591,47.0851269881201],[-122.659841996411,47.0851171072687],[-122.65988967307,47.0851087903384],[-122.659957579978,47.0850973248817],[-122.660056008078,47.085080701813],[-122.660222923149,47.0850534379658],[-122.660270534158,47.0850459232308],[-122.660271493734,47.0850457721447],[-122.660389709617,47.0850271139103],[-122.66055720565,47.0850016037411],[-122.66072471967,47.0849770009879],[-122.660825718032,47.0849627251497],[-122.660893990965,47.0849530709276],[-122.669778133554,47.0837207398204],[-122.671117141343,47.0835350046368],[-122.673305503046,47.0832314537686],[-122.674185592191,47.0831093761968],[-122.674196718604,47.0831077196456],[-122.67420777307,47.0831058490558],[-122.674544648317,47.0830453480644],[-122.67455840075,47.0830426986616],[-122.674572005693,47.0830397174091],[-122.674664048607,47.0830183009539],[-122.674921267303,47.0830183576112],[-122.674845365421,47.0864544378221],[-122.674716444009,47.0898687490436],[-122.669964633161,47.0897440148744],[-122.669949201694,47.0897438116277],[-122.669931691894,47.0897440733304],[-122.669914215369,47.0897448548412],[-122.669896805393,47.0897461579589],[-122.669879494343,47.0897479772874],[-122.669862316393,47.0897503110281],[-122.669845303918,47.0897531537851],[-122.669828489293,47.0897565010617],[-122.669811904895,47.0897603456635],[-122.669795581301,47.0897646821944],[-122.669779549986,47.0897694998626],[-122.669763842427,47.0897747896748],[-122.669748485604,47.0897805444366],[-122.669733512791,47.0897867488594],[-122.669718950969,47.0897933948493],[-122.669704826217,47.0898004680172],[-122.669691167313,47.0898079548733],[-122.66967799944,47.0898158419276],[-122.669665346878,47.0898241138918],[-122.669653235708,47.089832754578],[-122.669641688413,47.0898417477985],[-122.669630724778,47.0898510773654],[-122.669620368185,47.089860724393],[-122.66961063842,47.0898706699955],[-122.66960155167,47.0898808961865],[-122.669593127721,47.0898913831808],[-122.669585380961,47.0899021120928],[-122.669578326678,47.0899130613388],[-122.669571979263,47.0899242093349],[-122.669566348608,47.089935536296],[-122.669561448202,47.0899470197392],[-122.669557285241,47.0899586389801],[-122.669553867817,47.0899703706361],[-122.669551239998,47.0899820042661],[-122.669549346025,47.0899937044459],[-122.669548188598,47.0900054477933],[-122.669547771313,47.0900172154222],[-122.669519026282,47.0970367468485],[-122.665107413676,47.0970278696405],[-122.665082025815,47.0936323893234],[-122.665081578852,47.0936207799751],[-122.66508041333,47.0936091949085],[-122.665078529251,47.093597654808],[-122.665075932009,47.09358617766],[-122.665072513686,47.0935744460039],[-122.665068350724,47.0935628267631],[-122.665063450318,47.0935513433199],[-122.665057818763,47.0935400163587],[-122.665051471348,47.0935288683626],[-122.665044417066,47.0935179191167],[-122.665036670306,47.0935071902047],[-122.665028244558,47.0934967032103],[-122.665019157808,47.0934864770193],[-122.665009427143,47.0934765314169],[-122.664999069651,47.0934668843893],[-122.664988106016,47.0934575548224],[-122.664976556923,47.0934485616019],[-122.664964444853,47.0934399209157],[-122.664951792291,47.0934316489515],[-122.664938624418,47.0934237618972],[-122.664924962817,47.0934162750411],[-122.664910838065,47.0934092018732],[-122.664896274443,47.0934025558833],[-122.664881299832,47.0933963505612],[-122.664865943908,47.0933905966987],[-122.664850234551,47.0933853068864],[-122.664834202337,47.0933804892182],[-122.664817877843,47.0933761535867],[-122.664801291646,47.0933723089849],[-122.664784476123,47.093368960809],[-122.664767461849,47.093366118052],[-122.664750282999,47.0933637852106],[-122.664733944116,47.0933620531163],[-122.664717514402,47.0933607832736],[-122.664701020835,47.0933599747831],[-122.664684493095,47.0933596321414],[-122.654295936708,47.0932898429519],[-122.654293949206,47.0932898330594],[-122.647016399587,47.0932649766974],[-122.647034000219,47.0899386983123],[-122.647034002018,47.0899377063601],[-122.647034001118,47.0899370579489]]]],"type":"MultiPolygon"}'
```

running one query:

```sh
$ sh test.sh
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"652.940459ms"}
```

running 1000 queries in parallel batches of 100 (write the last command to test.sh):

```sh
$ parallel -N0 -j100 sh test.sh ::: {1..1000}

{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"3.082833808s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"2.558584174s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"2.80975919s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"1.976939971s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"4.018884319s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"4.576470115s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"4.521234967s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"4.149337203s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"4.310545036s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"4.836360865s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"5.399522789s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"5.182009147s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"6.087325189s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"6.015644608s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"6.500364239s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"8.778744214s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"8.917659266s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"9.053223614s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"9.968221763s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"10.444428779s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"11.416430736s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"11.703691015s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"12.187361445s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"12.832945691s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"13.010095585s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"13.904847537s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"13.640739004s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"14.42547465s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"15.034711299s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.616634312s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.249860353s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"14.833183001s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"15.547409747s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"14.882957865s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.613486954s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"17.153866396s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"17.808721787s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"14.961588382s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"15.403397251s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"14.521312052s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"18.195681938s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.266105593s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"13.2929794s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"17.666107916s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.763498471s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"17.610196427s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.302484908s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"15.376121672s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"18.122655003s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.977419248s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.351658579s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"18.115921466s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"17.51835791s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.519010885s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.481488974s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.914119911s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"13.613081773s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"15.812483658s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"15.011833662s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.191907725s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"15.556651284s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"15.580683646s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.279573789s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"20.101686843s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.672965083s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"19.273339291s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.740515613s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"17.147723387s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"18.44793932s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"19.072725036s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.43820253s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"17.296930539s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"15.104731226s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"15.081945215s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.74538216s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"17.631052185s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"14.310308587s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"17.372074139s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"17.535906458s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"20.576981837s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"16.262812826s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"21.034093946s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"19.723692497s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"17.616777802s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"20.070543891s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"19.525775617s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"19.71609525s"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"20.017285427s"}
```

interestingly enough the time it takes as this runs actually grows over time, so the first ones in took ~3 sec and halfway through it grows to 20s and sits there for the rest of the test.

the concurrency vs max time looks like this:

100 = 20s
200 = 30s
300 = 1m 30s

**Comment by tidwall** [comment]
Hi contra,  
The attached aof file is failing to load. I think it actually belongs to a Redis instance, not Tile38.

**Comment by tidwall** [comment]
I think the slowness is because of the size of the shapes. Both the number of points and the geographic size.

The most basic algorithm that Tile38 uses for detecting intersecting shapes is:

1) Reduce the query shape to it's minimum bounding rectangle. 
2) Search for the collection r-tree for intersecting rectangles.
3) Raycast the actual shapes against one another.

A large minimum bounding rectangle will cause a lot of hits from the r-tree. 
A lot of points in the shape will complicate the [raycasting](https://github.com/tidwall/tile38/tree/204b3ef7246f0091c27d937581e74b3db626a2a2/geojson/poly) process.

The USA shape alone is over 2MB and nearly half the size of the database.

When I load it on a map:

https://gist.github.com/tidwall/e665429e2ffe7f4716bd6d994030fdc7

I can see that it includes all states and territories. It's MBR encompasses more than half the world. And it has a lot of points.

A couple of idea to reduce query time:

**Simplify the shapes**

When I used the [simplify-geojson](https://github.com/maxogden/simplify-geojson) tool on the USA geometry the `./test.sh` went from 550ms to 130ms. 

```
cat usa.geojson | simplify-geojson -t 0.01
```

*For some reason the `simplify-geojson` requires `Feature` types, so I had to wrap the USA MultiPolygon in a Feature* 

**Break up geographically large MultiPolygons into separate geometries**

This will ensure that the each polygon will get its own rectangle in the r-tree. So the lower 48, Alaska, and various islands won't share the same rect.

Perhaps there're other tricks that could help. These are the two ideas that came to mind.

**Comment by contra** [comment]
@tidwall We're using it to legally determine where things are in countries/cities/etc. so simplifying would have things pop up in the wrong places sometimes. The country shapes are already simplified to maritime borders which removes most of the complexity (normal borders are 12MB for the USA) so it's about as small as it can get.

Is it possible that tile38 could have an optimization where it breaks down multipolygons into separate bounding boxes, making step 2 more selective? I could see this being really useful for anyone working with complex geometries.

**Comment by tidwall** [comment]
Perhaps a good first-step optimization would be to change the memory layout of the MultiPolygon.
Right now the points are stored as a `[][][]Position`. But if we instead store it as `[]Polygon` we may be able take advantage of the of bbox separation that comes built-in with all objects. It'll take up a little more memory but should help complex geometries.

**Comment by tidwall** [comment]
I just pushed an update to master using the separate bounding box idea. 

```
$ sh test.sh
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"15.426825ms"}
```


```
$ parallel -N0 -j100 sh test.sh ::: {1..1000}

{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"23.425412ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"23.688069ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"27.109546ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"23.389352ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"25.811838ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.094466ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.594458ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"26.315128ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"26.35796ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"23.923305ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"28.456937ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"29.889519ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.781063ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"28.619942ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"27.134521ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"25.879232ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"27.036367ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"26.341822ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.794387ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.371693ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"38.207006ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"25.279381ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"25.333678ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.098771ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"29.584999ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.64945ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"23.657102ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.131046ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"34.403827ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"23.859966ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"25.859089ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"23.228497ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"30.953587ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"23.010212ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.113372ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.276619ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"23.520024ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"23.400704ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.317942ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"25.750889ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"23.034372ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"23.66489ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"21.882846ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"23.24911ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"25.808271ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.392985ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.861074ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"27.543324ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.259123ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"23.595463ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"25.943864ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"27.445268ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"25.009951ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"22.374159ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"28.236124ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"25.631607ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"39.850402ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"31.925068ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"38.800466ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"33.962937ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"33.975492ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"23.317421ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.505824ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.182655ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"39.367853ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"26.772535ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.680694ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"34.393907ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"24.310378ms"}
{"ok":true,"ids":["usa","earth"],"count":2,"cursor":0,"elapsed":"26.048343ms"}
...
```

Stays steady and finishes in about 12 seconds.

**Comment by contra** [comment]
@tidwall Wow - that is quite the improvement, almost a 2000x reduction. Easily makes tile38 the fastest for doing multipolygon intersections. Possible to get this out in a release? I can give it a solid test on some staging systems today and report back.

**Comment by tidwall** [comment]
I can add it to the next patch release. I'll wait until you finish your tests on staging. I also want to add a some more unit tests.

**Comment by contra** [comment]
@tidwall Still have a significant number of requests that are spending ~22s on tile38. You can replace test.sh with this:

```sh
./tile38-cli 'INTERSECTS boundaries IDS OBJECT {"coordinates":[[[[-75.1264107875263, 39.946586232976635], [-75.12670313192828, 39.945590164921335], [-75.12700499439612, 39.94456163518478], [-75.12721954350499, 39.944575015700075], [-75.12692989481853, 39.945561938336546], [-75.1266174628429, 39.946626461326616], [-75.1264107875263, 39.946586232976635]]]],"type":"MultiPolygon"}'
```

Having a hard time reproducing 22s locally but I can at least get it up to a second or two per call, so I can see how under high concurrency it would start to grow like the original ticket. We're doing ~8k requests per minute. Based on traces this happens with all input geometry types.

**Comment by tidwall** [comment]
I'm not seeing the high number of seconds locally either.

With your latest command:

```
$ time parallel -N0 -j100 sh test.sh ::: {1..1000}
```

```
real	0m7.768s
user	0m9.539s
sys	0m13.624s
```

I could be off base here and without knowing anything about your staging server; I'm wondering if there isn't something else causing the bottleneck on the staging server, such as network ulimit, cpu, etc. 

There's the dev command `SLEEP seconds` for debugging purposes. This puts the server to sleep and idly blocks other incoming connections for N seconds. *I just pushed an update moments ago that allows for sub-seconds, so you'll need to pull the latest*

I started the server with the `--dev` switch.

```
./tile38-server --dev
```

Updated test.sh to block for 1ms per connection.

```
./tile38-cli 'SLEEP 0.001'
```

And ran your parallel command.

```
$ time parallel -N0 -j100 sh test.sh ::: {1..1000}
```

```
real	0m6.424s
user	0m7.695s
sys	0m12.076s
```

On my system the INTERSECTS script is not much slower than SLEEP script. Which makes me think that the INTERSECTS command is preforming well. 

I'm curious if the staging server is getting low numbers with SLEEP but high with INTERSECTS. If they are both similarly high then it might be the network, otherwise it's possibly due to cpu or slow query on Tile38.

**Comment by tidwall** [comment]
One more thing, Tile38 likes to run on a multicore system. It does work fine single-threaded, but you'll see occasional spikes in command duration.

To run Tile38 single-threaded: 

```
GOMAXPROCS=1 go run cmd/tile38-server/main.go
```

Then run the script locally and you'll probably see a few spikes, maybe even in the seconds.

**Comment by tidwall** [comment]
Oh and one more thing... 🤪

The `tile38-cli` command isn't the most efficient way to communicate with the server. For low frequency it's fine, but if you executing lots of commands then I recommend use a Redis client with connection pooling. Tile38 (like Redis) is optimized to handle lots of commands over fewer connections. 
I use [Redigo](https://github.com/garyburd/redigo).

**Comment by contra** [comment]
@tidwall We're just running the repo dockerfile on a kube cluster, so only getting 1 core. That would explain the huge gap between local (8 cores) and staging (1 core). Is there a point of diminishing returns for # of cpus given to tile38?

We're using https://github.com/phulst/node-tile38 to run queries.

**Comment by tidwall** [comment]
Good question. I'll try to get an answer to you, but first I want to look into why the single threaded blips are so big. Using `GOMAXPROCS=1`, my computer shows all is running smoothly at 25ms, then does a quick jump to 700ms  and back down again, at one second intervals. 

Something doesn't smell right.

**Comment by contra** [comment]
@tidwall Adding more cores did help somewhat - went from 1 to 4, avg time dropped from ~8s to ~3s (ignore the missing chunk in the middle).

![image](https://user-images.githubusercontent.com/425716/37169759-cfd924fe-22d6-11e8-981c-c241c030f324.png)

**Comment by tidwall** [comment]
That's good info. My testing is showing, at least for your multipolygon query, that 3+ cores can handle the load pretty smoothly. 

But something else might help is minimizing the number of concurrent connections. I think that the `-j100` flag starts up 100 connections at the same time, and then Tile38 needs to fire up 100 goroutines and do a lot of context switching. With 4+ cores it doesn't seem to matter much, but with less cores I found that lowering the `-j100` down to something the server can manage smoothed out the load. 

For example, I ran a single-threaded server:

```
GOMAXPROCS=1 ./tile38-server
```

And then...

```
time parallel -N0 -j4 sh test.sh ::: {1..1000}
```
```
real	0m14.193s
user	0m7.567s
sys	0m11.089s
```

Most responses where around 12ms-15ms with the max occasionally jumping to 45ms.

But with...

```
time parallel -N0 -j100 sh test.sh ::: {1..1000}
```
```
real	0m15.224s
user	0m8.630s
sys	0m13.630s
```

It was actually a little slower, with min around 12ms-15ms and the max shooting over a 1 second.

So if you do go with less cores on the server, then try to keep your client connections not much more than 2-4x that number. I think that this will ensure a more constant response time. 

Also use connection pooling. :)

**Comment by contra** [comment]
@tidwall Yeah, my next step is forking node-tile38 and adding connection pooling. Right now it uses stock node-redis to talk to tile38 which pipelines everything over 1 connection. I'll post once I've done that with the results.

**Comment by tidwall** [comment]
Tile38 does handle pipelining very well. This is where the a single packet contains multiple commands. You should see some big boosts when you use it for small commands. You'll also want to have some type of connection pooling that reuses existing connections in conjunction with pipelining.

You probably won't see a boost with pipelining for big commands (over 4096 bytes) since the routers will often break up the packets before they reach the server.

**Comment by tidwall** [comment]
I pushed a minor release that includes this a fix to this issue.

**Comment by contra** [comment]
I think this is resolved so I'm going to close this - we're seeing some slowdowns for this case but I think they are unrelated.
