### ISSUE TITLE
linestring intersection doesn't work

### ISSUE THREAD

**Issue by contra** [tidwall/tile38#281]
db: https://github.com/tidwall/tile38/files/1776947/appendonly.aof.zip (same as #267)

test.sh:
```sh
./tile38-cli 'INTERSECTS boundaries IDS OBJECT {"coordinates":[[-74.01020234,40.71291224],[-74.00666661,40.71911552]],"type":"LineString"}'
./tile38-cli 'INTERSECTS boundaries IDS OBJECT {"coordinates":[-74.01020234,40.71291224],"type":"Point"}'
./tile38-cli 'INTERSECTS boundaries IDS OBJECT {"coordinates":[-74.00666661,40.71911552],"type":"Point"}'
```

repro:

```sh
$ sh test.sh

{"ok":true,"ids":[],"count":0,"cursor":0,"elapsed":"16.089059ms"} # the linestring
{"ok":true,"ids":["usa-ny-new-york-state","usa","earth","usa-ny-new-york-city"],"count":4,"cursor":0,"elapsed":"16.337672ms"} # the start point
{"ok":true,"ids":["usa-ny-new-york-state","usa","earth","usa-ny-new-york-city"],"count":4,"cursor":0,"elapsed":"16.3557ms"} # the end point
```

each point on its own returns the correct value, but in a linestring they return no results. expected result is that it returns any intersection that occurs along the linestring, and it would work the same way with a multilinestring as well.

**Comment by tidwall** [comment]
I've located the issue. Working on it now. Thanks

**Comment by tidwall** [comment]
I pushed a fix to master.

**Comment by tidwall** [comment]
Hold your horses. There's a performance regression I need to look into.

**Comment by tidwall** [comment]
Ok now it's back on track.

**Comment by contra** [comment]
@tidwall I just tested it and still getting the same results.

**Comment by contra** [comment]
Ah nevermind, was on the old version still. Seems fixed.
