### ISSUE TITLE
Tile38 server memory usage seems to be increasing indefinitely

### ISSUE THREAD

**Issue by Morgiflute** [tidwall/tile38#621]
We have quite a modest usage of a tile38 server and it's geofencing capabilities. We currently have 11 hooks, and about one or two thousand of data points at a time. Each data injected have a TTL of 10s.

The issue is that the memory usage keep increasing while the number of data remain the same. After several days, we reach up to 3Go of ram ! While at the start, tile38 server uses about 300mB of ram.
It may be a memory leak.

![gc](https://user-images.githubusercontent.com/89079874/129722420-b795f24c-7afa-4a33-ba3b-1be9b829a11a.PNG)
![gc](https://user-images.githubusercontent.com/89079874/129722999-facf3342-61b9-45c8-a9c1-525dc32df7fa.PNG)
![server](https://user-images.githubusercontent.com/89079874/129723003-3ccf2ace-66c0-465a-8592-444229b482b8.PNG)
![tile38](https://user-images.githubusercontent.com/89079874/129723004-e3c47d48-bc0a-4eeb-a58c-d6bb2a69e7b4.PNG)
![pprof](https://user-images.githubusercontent.com/89079874/129723005-7b927ef8-e228-4101-b268-2310abd8057a.jpg)
![pprof002](https://user-images.githubusercontent.com/89079874/129723007-6908a205-3013-4f52-b8e4-1357b4a08826.jpg)

**Comment by iwpnd** [comment]
Are you using kafka hooks?

**Comment by Morgiflute** [comment]
No, I'm using redis pub/sub channel @iwpnd 
I've seen a bug fix for kafka hooks memory leak in the changelog, but we are not concerned :/

**Comment by tidwall** [comment]
@Morgiflute 
Your attached graphs show gopher.Lua usage. Are you using Lua?

**Comment by tidwall** [comment]
Also, can you give an example of what your SET and SETCHAN operations look like?
I would like to reproduce the issue on my side. Thanks.

**Comment by Morgiflute** [comment]
@tidwall 
I'm not using LUA. To obtain these graphs, i've used the command `./tile38-server -pprofport 6060 -d /data`, using your docker image of tile38 1.22.6, then go tool pprof -web http://.../debug/pprof/heap

We have two collection of data: Points & tracks. This is how we insert data:

`SET track track1 EX 10 POINT <latitude> <longitude> <altitude>`
`SET point point1 EX 10 POINT <latitude> <longitude> <altitude>`

And here is how we subscribe to geofence events:

`SETCHAN track+zone1 WITHIN track FENCE DETECT inside COMMANDS set OBJECT {"type":"Polygon","coordinates":[[[4.69469051277219955,45.69030172148438],[5.126086639693051,45.935296107807725],[5.305332831063167,45.51485363603867],[5.305332831063167,45.51485363603867],[4.69469051277219955,45.69030172148438]]]}`
`SETCHAN plot+zone1 WITHIN point FENCE DETECT inside COMMANDS set OBJECT  {"type":"Polygon","coordinates":[[[4.69469051277219955,45.69030172148438],[5.126086639693051,45.935296107807725],[5.305332831063167,45.51485363603867],[5.305332831063167,45.51485363603867],[4.69469051277219955,45.69030172148438]]]}3`

Also, we are using redigo v1.8.3 with pubsubconn for subscribing geofence events

**Comment by tidwall** [comment]
@Morgiflute Thanks for the additional info.

**Comment by tidwall** [comment]
@Morgiflute I'm having trouble reproducing this issue.

I notice that you are using 1.22.6. Have you had an opportunity to try the 1.25.2? I'm wondering if this issue is happening in the latest version.

**Comment by Morgiflute** [comment]
@tidwall I've just installed version 1.25.2, and yep, it seems to perform much better in term of memory usage :)
Here are the differents graphs of v1.22.6 vs 1.25.2 for the same input and hooks:

## 1.22.6:
![tile1226](https://user-images.githubusercontent.com/89079874/129909547-6ec0bf0f-d5f1-40d1-90fe-f649b3ed9769.PNG)

## 1.25.2:
![tile1252](https://user-images.githubusercontent.com/89079874/129909553-0a17f98d-6662-4e7b-bad4-ebb5f0c84061.PNG)

I'll continue to monitor, but it looks promising 😉🤘

**Comment by tidwall** [comment]
That's does look promising.

**Comment by Morgiflute** [comment]
Mmmh, I'm sorry to come back here, but it seems like the issue is still here 🤔

![tilebug1252](https://user-images.githubusercontent.com/89079874/130045326-85b7f6b7-034b-4577-ad18-f3d5453a4a3d.PNG)

**Comment by tidwall** [comment]
Ok. I'll poke around a bit and see if I find what's up.

**Comment by Morgiflute** [comment]
Oh, and by the way, what is the good way to use tile38 if we only need geofencing, meaning we don't need to store the data ?
Is it a good idea to use TTL ? And how to choose it ?

**Comment by tidwall** [comment]
I found a leak. It may be related to this issue. 
I pushed an update moments ago. You can test using the "edge" docker image

**Comment by tidwall** [comment]
> Oh, and by the way, what is the good way to use tile38 if we only need geofencing, meaning we don't need to store the data ?

If you don't care about storing data then you can start Tile38 with the `--appendonly no` flag.

> Is it a good idea to use TTL ? 

A TTL is useful for when you have objects that are short-lived or that change often. Like a vehicle that sends a moving position every few seconds or so. In that case, you can set a TTL on every SET operation, and when the vehicle stops sending data, Tile38 will automatically delete the old position.

> And how to choose it ?

This depends a lot on the your use case. There's no specific rule. But, I know of a ride share organization that sends positions for each vehicle every 5-10 seconds uses 30-45 second TTL.

> Can a low TTL impact performance ? Memory usage ?

There is no difference in performance between a low or high TTL. It matters more the number objects with TTLs. Tile38 maintains a queue for all objects with TTLs. The size of that queue may impact performance a little bit, if it gets massive. 

> Also, is it OK to use the character "+" on channel names ?

Yes, there are no restrictions for the characters you use collection keys, objects ids, channels, etc.
But a colon ":" is more common separator character.

**Comment by Morgiflute** [comment]
Oh great news ! I'm looking forward testing it shortly, I'll keep you updated 🙂

Thanks !

**Comment by Morgiflute** [comment]
So i've downloaded your 'edge' version of docker image, but it seems like the memory leak issue is still here.
The slope that memory usage is taking is alarming :/

**Comment by tidwall** [comment]
I guess I’m unable to find the leak you are running into. Right now I’m searching in the dark. Would you be able to provide me with a test application or exact steps that will reproduce what you are seeing?
